# Generated by Selenium IDE
import pytest
from model.group import Group
from fixture.application import Application


@pytest.fixture
def app(request):
    fixture = Application()
    request.addfinalizer(fixture.destroy)
    return fixture

def test_testaddgroup3(app):
    app.session.login(username="admin", password="secret")
    app.group.create(Group(name="tele", header="mnb", footer="ertio"))
    app.session.logout()

def test_testaddgroup3_2(app):
    app.session.login(username="admin", password="secret")
    app.group.create(Group(name="", header="", footer=""))
    app.session.logout()


