# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestTestaddgroup3():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def open_home_page(self):
      self.driver.get("http://localhost/addressbook/")
      self.driver.set_window_size(1048, 1040)

    def login(self):
      self.driver.find_element(By.NAME, "user").click()
      self.driver.find_element(By.NAME, "user").send_keys("admin")
      self.driver.find_element(By.NAME, "pass").click()
      self.driver.find_element(By.NAME, "pass").send_keys("secret")
      self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(7)").click()

    def open_groups_page(self):
      self.driver.find_element(By.LINK_TEXT, "groups").click()
      self.driver.find_element(By.NAME, "new").click()

    def create_group(self):
      self.driver.find_element(By.NAME, "group_name").click()
      self.driver.find_element(By.NAME, "group_name").send_keys("tele")
      self.driver.find_element(By.NAME, "group_header").click()
      self.driver.find_element(By.NAME, "group_header").send_keys("mnb")
      self.driver.find_element(By.NAME, "group_footer").click()
      self.driver.find_element(By.NAME, "group_footer").send_keys("ertio")
      self.driver.find_element(By.NAME, "submit").click()


    def return_groups(self):
      self.driver.find_element(By.LINK_TEXT, "groups").click()

    def logout(self):
      self.driver.find_element(By.LINK_TEXT, "Logout").click()


    def test_testaddgroup3(self):
        self.open_home_page()
        self.login()
        self.open_groups_page()
        self.create_group()
        self.return_groups()
        self.logout()

    def teardown_method(self, method):
        self.driver.quit()


if __name__ == '__main__':
    TestTestaddgroup3()
