# Generated by Selenium IDE
import pytest
from selenium import webdriver
from group import Group
from application import Application


@pytest.fixture
def app(request):
    fixture = Application()
    request.addfinalizer(fixture.destroy)
    return fixture

def test_testaddgroup3(app):
    app.login(username="admin", password="secret")
    app.create_group(Group(name="tele", header="mnb", footer="ertio"))
    app.logout()

def test_testaddgroup3_2(app):
    app.login(username="admin", password="secret")
    app.create_group(Group(name="", header="", footer=""))
    app.logout()


