# Generated by Selenium IDE
from selenium import webdriver
from selenium.webdriver.common.by import By
from model.group import Group

class TestTestaddgroup3():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def open_home_page(self):
      self.driver.get("http://localhost/addressbook/")
      self.driver.set_window_size(1048, 1040)

    def login(self, username, password):
      self.open_home_page()
      self.driver.find_element(By.NAME, "user").click()
      self.driver.find_element(By.NAME, "user").send_keys(username)
      self.driver.find_element(By.NAME, "pass").click()
      self.driver.find_element(By.NAME, "pass").send_keys(password)
      self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(7)").click()

    def open_groups_page(self):
      self.driver.find_element(By.LINK_TEXT, "groups").click()
      self.driver.find_element(By.NAME, "new").click()

    def create_group(self, group):
      self.open_groups_page()
      self.driver.find_element(By.NAME, "group_name").click()
      self.driver.find_element(By.NAME, "group_name").send_keys(group.name)
      self.driver.find_element(By.NAME, "group_header").click()
      self.driver.find_element(By.NAME, "group_header").send_keys(group.header)
      self.driver.find_element(By.NAME, "group_footer").click()
      self.driver.find_element(By.NAME, "group_footer").send_keys(group.footer)
      self.driver.find_element(By.NAME, "submit").click()
      self.return_groups()


    def return_groups(self):
      self.driver.find_element(By.LINK_TEXT, "groups").click()

    def logout(self):
      self.driver.find_element(By.LINK_TEXT, "Logout").click()


    def test_testaddgroup3(self):
        self.login(username="admin", password="secret")
        self.create_group(Group(name="tele", header="mnb", footer="ertio"))
        self.logout()

    def test_testaddgroup3_2(self):
        self.login(username="admin", password="secret")
        self.create_group(Group(name="", header="", footer=""))
        self.logout()

    def teardown_method(self, method):
        self.driver.quit()


if __name__ == '__main__':
    TestTestaddgroup3()
